export function closes(c){return c.map(x=>Number(x.close)).filter(Number.isFinite)}
export function sma(v,p){if(v.length<p)return null;return v.slice(-p).reduce((a,b)=>a+b,0)/p}
export function ema(v,p){if(v.length<p)return null;const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
export function rsi(v,p=14){if(v.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1],gain=Math.max(d,0),loss=Math.max(-d,0);ag=((ag*(p-1))+gain)/p;al=((al*(p-1))+loss)/p}if(al===0)return 100;return 100-100/(1+ag/al)}
export function atr(c,p=14){if(c.length<=p)return null;const tr=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<tr.length;i++)a=((a*(p-1))+tr[i])/p;return a}
export function macd(v,f=12,s=26,sg=9){if(v.length<s+sg)return null;const line=[];for(let i=s;i<=v.length;i++){const x=v.slice(0,i);line.push(ema(x,f)-ema(x,s))}const signal=ema(line,sg);return {line:line.at(-1),signal,histogram:line.at(-1)-signal}}
export function highest(c,p){return c.length<p?null:Math.max(...c.slice(-p).map(x=>x.high))}
export function lowest(c,p){return c.length<p?null:Math.min(...c.slice(-p).map(x=>x.low))}

export function bollinger(v,p=20,mult=2){if(v.length<p)return null;const a=v.slice(-p),mid=a.reduce((x,y)=>x+y,0)/p;const variance=a.reduce((x,y)=>x+(y-mid)**2,0)/p,sd=Math.sqrt(variance);return{middle:mid,upper:mid+mult*sd,lower:mid-mult*sd,width:mid?((2*mult*sd)/mid):0}}
export function stochastic(c,p=14,smooth=3){if(c.length<p)return null;const r=c.slice(-p),hi=Math.max(...r.map(x=>x.high)),lo=Math.min(...r.map(x=>x.low)),last=r.at(-1);const k=hi===lo?50:((last.close-lo)/(hi-lo))*100;const ks=[];for(let i=Math.max(p-1,c.length-smooth);i<c.length;i++){const q=c.slice(i-p+1,i+1),h=Math.max(...q.map(x=>x.high)),l=Math.min(...q.map(x=>x.low));ks.push(h===l?50:((c[i].close-l)/(h-l))*100)}return{k,d:ks.reduce((a,b)=>a+b,0)/ks.length}}
export function adx(c,p=14){if(c.length<=p*2)return null;const tr=[],plus=[],minus=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];tr.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)));const up=x.high-q.high,down=q.low-x.low;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)}let atrN=tr.slice(0,p).reduce((a,b)=>a+b,0)/p,pN=plus.slice(0,p).reduce((a,b)=>a+b,0)/p,mN=minus.slice(0,p).reduce((a,b)=>a+b,0)/p;const dx=[];for(let i=p;i<tr.length;i++){atrN=((atrN*(p-1))+tr[i])/p;pN=((pN*(p-1))+plus[i])/p;mN=((mN*(p-1))+minus[i])/p;const pi=100*pN/atrN,mi=100*mN/atrN,den=pi+mi;dx.push(den?100*Math.abs(pi-mi)/den:0)}if(dx.length<p)return null;let a=dx.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<dx.length;i++)a=((a*(p-1))+dx[i])/p;return a}

export function movingAverages(v){return{ma20:sma(v,20),ma50:sma(v,50),ma100:sma(v,100),ma200:sma(v,200),ema20:ema(v,20),ema50:ema(v,50),ema100:ema(v,100),ema200:ema(v,200)}}
export function ichimoku(c,tenkan=9,kijun=26,senkou=52){if(c.length<senkou)return null;const mid=(p)=>{const r=c.slice(-p),hi=Math.max(...r.map(x=>x.high)),lo=Math.min(...r.map(x=>x.low));return(hi+lo)/2};const t=mid(tenkan),k=mid(kijun),spanA=(t+k)/2,spanB=mid(senkou),price=c.at(-1).close;return{tenkan,kijun,senkouA:spanA,senkouB:spanB,price,aboveCloud:price>Math.max(spanA,spanB),belowCloud:price<Math.min(spanA,spanB),cloudBullish:spanA>spanB}}
