function body(x){return Math.abs(x.close-x.open)}
function range(x){return x.high-x.low}
function bull(x){return x.close>x.open}
function bear(x){return x.close<x.open}
function near(a,b,t){return Math.abs(a-b)<=t}
function pivots(c,left=2,right=2){const out=[];for(let i=left;i<c.length-right;i++){let hi=true,lo=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(c[j].high>=c[i].high)hi=false;if(c[j].low<=c[i].low)lo=false}if(hi)out.push({i,type:"high",price:c[i].high});if(lo)out.push({i,type:"low",price:c[i].low})}return out}
export function candlePatterns(c){if(c.length<5)return{bullish:[],bearish:[],neutral:[]};const a=c.at(-1),p=c.at(-2),pp=c.at(-3),ar=Math.max(range(a),1e-9),b=body(a),up=a.high-Math.max(a.open,a.close),dn=Math.min(a.open,a.close)-a.low;const bullish=[],bearish=[],neutral=[];if(b<=ar*.12)neutral.push("doji");if(dn>=b*2&&up<=b*.8)bullish.push("hammer");if(up>=b*2&&dn<=b*.8)bearish.push("shooting_star");if(bull(a)&&bear(p)&&a.open<=p.close&&a.close>=p.open)bullish.push("bullish_engulfing");if(bear(a)&&bull(p)&&a.open>=p.close&&a.close<=p.open)bearish.push("bearish_engulfing");if(bear(pp)&&bull(p)&&bull(a)&&a.close>pp.open&&p.close<pp.open)bullish.push("morning_star");if(bull(pp)&&bear(p)&&bear(a)&&a.close<pp.open&&p.close>pp.open)bearish.push("evening_star");return{bullish,bearish,neutral}}
export function marketStructure(c){const ps=pivots(c);if(ps.length<4)return{bos:null,choch:null,swingHigh:null,swingLow:null};const highs=ps.filter(x=>x.type==="high"),lows=ps.filter(x=>x.type==="low"),lastH=highs.at(-1),prevH=highs.at(-2),lastL=lows.at(-1),prevL=lows.at(-2),close=c.at(-1).close;const bos=close>lastH.price?"bullish":close<lastL.price?"bearish":null;const priorTrend=prevH&&prevL&&lastH&&lastL?(lastH.price>prevH.price&&lastL.price>prevL.price?"bullish":lastH.price<prevH.price&&lastL.price<prevL.price?"bearish":"range"):null;const choch=bos&&priorTrend&&bos!==priorTrend?bos:null;return{bos,choch,swingHigh:lastH?.price??null,swingLow:lastL?.price??null}}
export function liquiditySweep(c,lookback=20){if(c.length<lookback+1)return null;const prior=c.slice(-(lookback+1),-1),a=c.at(-1),hi=Math.max(...prior.map(x=>x.high)),lo=Math.min(...prior.map(x=>x.low));if(a.high>hi&&a.close<hi)return"bearish";if(a.low<lo&&a.close>lo)return"bullish";return null}
export function fairValueGap(c){if(c.length<3)return null;const a=c.at(-3),d=c.at(-1);if(a.high<d.low)return{type:"bullish",low:a.high,high:d.low};if(a.low>d.high)return{type:"bearish",low:d.high,high:a.low};return null}
export function orderBlock(c){if(c.length<5)return null;const s=marketStructure(c);if(!s.bos)return null;for(let i=c.length-2;i>=Math.max(0,c.length-12);i--){const x=c[i];if(s.bos==="bullish"&&bear(x))return{type:"bullish",index:i,low:x.low,high:x.high};if(s.bos==="bearish"&&bull(x))return{type:"bearish",index:i,low:x.low,high:x.high}}return null}
export function classicalPatterns(c){if(c.length<10)return{doubleTop:false,doubleBottom:false,rangeBreakout:null};const ps=pivots(c),hs=ps.filter(x=>x.type==="high").slice(-2),ls=ps.filter(x=>x.type==="low").slice(-2),last=c.at(-1),tol=Math.max(range(last)*1.5,last.close*.001);const doubleTop=hs.length===2&&near(hs[0].price,hs[1].price,tol);const doubleBottom=ls.length===2&&near(ls[0].price,ls[1].price,tol);const hi=Math.max(...c.slice(-10,-1).map(x=>x.high)),lo=Math.min(...c.slice(-10,-1).map(x=>x.low));return{doubleTop,doubleBottom,rangeBreakout:last.close>hi?"bullish":last.close<lo?"bearish":null}}
export function analyzePatterns(c){return{candles:candlePatterns(c),structure:marketStructure(c),liquiditySweep:liquiditySweep(c),fvg:fairValueGap(c),orderBlock:orderBlock(c),classical:classicalPatterns(c)}}